# Project language
language: cpp

# Allows use container-based infrastructure
sudo: false

addons:

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
  sonarcloud:
    organization: "adshares-github"
    token:
      secure: secure: "hjk5bSXk8iMlLaaeuo2ow7plQLs5fRNUvzqn/zNhxiQfINFFDGGo5F7uA+LlZOFOg/DrpiKXhCAHzKD0X9IlXFFF3yfQKFP6p98THq1Q9/tT3gVVcS+VI2zBLIre7+Z0+clKQAbV+qR497yu9vhIenCNyaAUywtHBDCWmiu/PbjmCBZo2FuijuW0y/eRoxCDGRs39JkZ8H13O6JnyzJdR33QeZRfJCJ9j/Ouw0/UZoTbC2i4vGDNrBJ348oPZFoQzWOelhwPq3gX8mWsfAoLHiFMm5fV88vr8QBclnkJnxgC/q1tpUBwcCYmBfyxRbn7bkDM+uX20Arj0wH2vLUVn2d0m2PKFlMqV5KAUPcDaCEgvFw3T70y90AjPK2kul2IrNcx44HTDRwfe6xRlibTwJ2OsxjFMHSOB2oXi+ZyURUWfdULy6nYcvFbXEhA6bT75mzM4u2ApBgtITKdRY/3yKQudH6ELCb7tJEthJX+cKQY2iTNy5SoVcHyQwC1jLxBQZtt0ha49HvSk0aMUT5u5tMwlA/wN5ITzF3+/7J8B1A+wTjCMC9p9ewybOz6dZZw7NfV0ygI7TL0Qe5b4DVMq2ezH99XkSuhAvaAfhcyazIcUqZgk+m85g6r2e8LVt9pKyejObFEYsE71C1izt//PgOfRkkND5hPMyc6k4rljbc="
    github_token:
      secure: "S/uDns/BWkrSpmSuWX5sJxLUrHiIBMT1C1oYr7VQNTB8rie5ld2L95NwXtd/mrj6mNd4dK/xcFw83z+Q/bUvc4tXjOJS84pSdXfB43/s3wJhZit055QgaCyDV+hN8di46/+LdAV7anoeAIBwrVi1DmG8xJGglrFR9QxUoYS0U2o56+CYd9L8KhvcwJUixjk31A3zF8vQ+OmTLlJFiMA52g63a0zz2uTfr5vrbjRrcvhmB7DX+BG+1YfH41N5dBw4bRfkqu/HOKKwnbizOZJtCxklnPfMJlubi+8S82QXZJ4BmOsMl/ZjyQxL7HWYa7D1nNGAcwhzGKXz5hevJJQVOdH1v/EihJRXBUrts9j1aS6OZ7bS3zRz+Lnr1PUYtW3hX4xVoyHSMxEv9ww6e646kPYnsMA0KcbBHwa+WppoPBAQEpS+SsdQ2VlDmNNhycia3ok5/ZHUG4yI0e/Fgr9PW+bVppNF1Hq3eqQRLvgUXpORVki6pz/Jd0aijLDukRhMCjfTehQfBVYhK3Xl8hB3MAy8tX3hpGzj+9M6Stam4UyB1kkgA3uiGJUTjM1cg3DzPpAIRfxYmqswGgEs6OdN/UcaPERjL9i/ON3TIjjpEw1TLLBnjEiGukL04PooCzHyaeo2nJO6QGLrocr+lVYYx2V/7zS7O2KPEzvHdGpmKqI="
    
env:
  - GCC_EVAL="CC=gcc-7 && CXX=g++-7"   
  
before_install:
  - eval "${GCC_EVAL}"
  - sudo apt-get install openssl libboost-all-dev libssl-dev

stages:
  - configure
  - build
  - quality
#  - test

jobs:
  include:
    # ED25519 test
    - stage: configure
      script:
        - cd ed25519
        - make -f Makefile.sse2
        - ./mytest
        - make clean
        - make
        - ./mytest
        - cd ..
  
    - stage: build
      script: make
      
    # Sonar Qube
    - stage: quality
      script: sonar-scanner
      
    # Selenium tests
    #- stage: test
    #  script:  

# After a build, send email notification with the build results
notifications:
  email: false
  slack:
    rooms:
      secure: "hnqTDsbo//IGwd629Vl1fBSpfJeAk0XE0VE5UD0Whub9ybHt6BRJ2EiUms6qPFLoypmlKsQUmXlG9d6Jx9VXyn0fkUd486mJ5qGjcLp59syUdpjO6BxCUIJo/xDBy2EZLgsdqzzFk3/s0I9lbAbbiYq3T+tTAiQgWQ2pC+ob5q3c8jV9bDJym7AwAe3tYbIKoB9v/h1Q8wPzWyrhPUKoxzAIiGtUOsiBREuuIIZi1mMQZz94RWyPJ2YlCCMbpP0ihDXhlamJIxSaqNo+4k/XbG0uoE1A+6eL3yFWDLbGMTk8NM8BbpFfJJ6xf+RL3bi0XBZYZlFOMPaogEXqzPBewcIp5cz4HApaX2tteiYdWQ3Z/erCIxnBiY9NdaqCNDjy+BxzLzb+uDJJoIfArOeDE9skv4tWVCEyY/myfitVs51zkHbyzmdpT79NdBcNASa0U7SW/33I5b5IXE+NWaDhpVa9Op/5VVY9jLmNzd5yvypJJf+ydF+PIyuxMpEUNPpuGYxlztYmbg5SmjxmOtk3dzBil9SudTWB1NZnnGFPOPLTfW0lGrSJLBLIxaHRQSc50ESoxb1aVlsxMOEuWYRjolSgWVPKSZGUFU8fydr99vxLvxtzgh6lx7S+0EfM/yUUJc/YJrN1wZxYOsYm3Pr0xNMxOWNIBo6PcEECNSfArro="
    on_success: change
    on_failure: always